<img src="http://2.bp.blogspot.com/-H2m-BFydExw/Wkc9gJQE8GI/AAAAAAAAcZI/pJhLUIEj9zMe2fmVsQuK2UWFbrVagaongCK4BGAYYCw/s0/%25E6%2588%2590%25E5%258A%259F%25E9%2581%258E%25E7%25A8%258B.png"
style="width:100px;height:100px;float:left"><br/><br/><br/><br/><br/>  
### 專案名稱: python測試  
### 功能描述:  練習pandas套件
### 版權所有: Dunk  
### 程式撰寫: Dunk  
### 撰寫日期：2020/02/11
### 改版日期:  
### 2020/02/11 增加Serise練習及Dataframe
### 2020/02/13 增加Dataframe
### 2020/02/14 處理缺失值
### 2020/02/15 處理join
### 2020/02/17 處理merge

In [2]:
'''資料清洗(Data Munging)'''
import pandas as pd
import numpy as np
import pprint
#顯示版本號
pprint.pprint(pd.__version__)

'0.25.1'

In [3]:
'''序列'''
data = pd.Series([0.25,0.5,0.75,1.0])
pprint.pprint(data)
pprint.pprint(data.values)
pprint.pprint(data.index)
pprint.pprint(data[1])
pprint.pprint(data[1:3])

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64
array([0.25, 0.5 , 0.75, 1.  ])
RangeIndex(start=0, stop=4, step=1)
0.5
1    0.50
2    0.75
dtype: float64

In [2]:
'''通用的數組，可以隨意設定索引'''
data = pd.Series([0.25,0.5,0.75,1.0],index=['a','b','c','d'])
pprint.pprint(data)
data = pd.Series([0.25,0.5,0.75,1.0],index=[33,44,121,45])
pprint.pprint(data)
#以字典設定
population_dict = {'a':123,'b':'afb','c':1.0,'d':'KKK'}
data = pd.Series(population_dict)
pprint.pprint(data)
pprint.pprint(data['a'])
pprint.pprint(data['b':'d'])
pprint.pprint(data[::-1])
#篩選過濾後結果
data_filter = pd.Series(population_dict,index=['a','c'])
pprint.pprint(data_filter)

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64
33     0.25
44     0.50
121    0.75
45     1.00
dtype: float64
a    123
b    afb
c      1
d    KKK
dtype: object
123
b    afb
c      1
d    KKK
dtype: object
d    KKK
c      1
b    afb
a    123
dtype: object
a    123
c      1
dtype: object

In [4]:
'''DataFrame為特殊的字典'''
area_dict={'Taipei':213,'Losangle':5322,'Taichung':'ppp'}
area = pd.Series(area_dict)
population_dict = {'a':123,'b':'afb','c':1.0,'d':'KKK','Taipei':'zzz'}
population = pd.Series(population_dict)
states = pd.DataFrame({'population':population,'area':area})
pprint.pprint(states)
#索引標籤
pprint.pprint(states.index)
#欄位名稱
pprint.pprint(states.columns)
pprint.pprint(states['area'])
#建立DataFrame對象
pprint.pprint(pd.DataFrame(population,columns=['population']))
pprint.pprint(pd.DataFrame([{'a':1,'b':3},{'b':8,'c':9}]))
#設定行列
pprint.pprint(pd.DataFrame(np.random.rand(3,2),columns=['foo','bar'],index=['a','b','c']))

         population  area
Losangle        NaN  5322
Taichung        NaN   ppp
Taipei          zzz   213
a               123   NaN
b               afb   NaN
c                 1   NaN
d               KKK   NaN
Index(['Losangle', 'Taichung', 'Taipei', 'a', 'b', 'c', 'd'], dtype='object')
Index(['population', 'area'], dtype='object')
Losangle    5322
Taichung     ppp
Taipei       213
a            NaN
b            NaN
c            NaN
d            NaN
Name: area, dtype: object
       population
a             123
b             afb
c               1
d             KKK
Taipei        zzz
     a  b    c
0  1.0  3  NaN
1  NaN  8  9.0
        foo       bar
a  0.831739  0.459890
b  0.085033  0.034302
c  0.980481  0.532029

In [13]:
'''索引，不可變更且為有序集合'''
ind = pd.Index([2,3,4,11,89])
pprint.pprint(ind)
pprint.pprint(ind[3:])
pprint.pprint(ind[:2])
pprint.pprint(ind[::2])
#邏輯操作
ind_a = pd.Index([2,3,4,11,89])
ind_b = pd.Index([2,3,5,11,87])
#交集
pprint.pprint(ind_a & ind_b)
#聯集
pprint.pprint(ind_a | ind_b)
#差集
pprint.pprint(ind_a ^ ind_b)

Int64Index([2, 3, 4, 11, 89], dtype='int64')
Int64Index([11, 89], dtype='int64')
Int64Index([2, 3], dtype='int64')
Int64Index([2, 4, 89], dtype='int64')
Int64Index([2, 3, 11], dtype='int64')
Int64Index([2, 3, 4, 5, 11, 87, 89], dtype='int64')
Int64Index([4, 5, 87, 89], dtype='int64')

In [9]:
'''數值取值與選擇'''
data = pd.Series([0.25,0.5,0.75,1.0],index=['a','b','c','d'])
pprint.pprint(data['a'])
pprint.pprint('a' in data)
pprint.pprint(data.keys())
pprint.pprint(list(data.items()))
#新增字典項目
data['e']=1.25
pprint.pprint(data)
#切片
pprint.pprint(data['a':'c'])
#隱式索引
pprint.pprint(data[0:2])
#掩碼
pprint.pprint(data[(data >0.3) & (data <0.8)])
#花哨
pprint.pprint(data[['a','e']])

0.25
True
Index(['a', 'b', 'c', 'd'], dtype='object')
[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]
a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64
a    0.25
b    0.50
c    0.75
dtype: float64
a    0.25
b    0.50
dtype: float64
b    0.50
c    0.75
dtype: float64
a    0.25
e    1.25
dtype: float64

In [15]:
'''索引器'''
data = pd.Series(['a','b','c'],index=[1,3,5])
pprint.pprint(data)
#顯式
pprint.pprint(data[1])
#隱式，容易與現行索引混淆
pprint.pprint(data[1:3])
#設定索引器(顯式)
pprint.pprint(data.loc[1])
pprint.pprint(data.loc[1:3])
#設定索引器(隱式)
pprint.pprint(data.iloc[1])
pprint.pprint(data.iloc[1:3])

1    a
3    b
5    c
dtype: object
'a'
3    b
5    c
dtype: object
'a'
1    a
3    b
dtype: object
'b'
3    b
5    c
dtype: object

In [5]:
'''DataFrame資料選擇'''
area = pd.Series({'a':1,'b':2,'c':3})
pop = pd.Series({'a':'Jack','b':'May','c':'Alice'})
data = pd.DataFrame({'area':area,'pop':pop})
pprint.pprint(data)
#選取資料
pprint.pprint(data['area'])
pprint.pprint(data.area)
pprint.pprint(data.area is data['area'])
#已有pop方法，所以不相同
pprint.pprint(data.pop is data['pop'])
#增加列
data['desc'] = data['area']/10
pprint.pprint(data)
pprint.pprint(data.values)
pprint.pprint(data.T)
pprint.pprint(data.values[0])
pprint.pprint(data['b':'c'])
pprint.pprint(data[1:2])
pprint.pprint(data[data.area>2])

   area    pop
a     1   Jack
b     2    May
c     3  Alice
a    1
b    2
c    3
Name: area, dtype: int64
a    1
b    2
c    3
Name: area, dtype: int64
True
False
   area    pop  desc
a     1   Jack   0.1
b     2    May   0.2
c     3  Alice   0.3
array([[1, 'Jack', 0.1],
       [2, 'May', 0.2],
       [3, 'Alice', 0.3]], dtype=object)
         a    b      c
area     1    2      3
pop   Jack  May  Alice
desc   0.1  0.2    0.3
array([1, 'Jack', 0.1], dtype=object)
   area    pop  desc
b     2    May   0.2
c     3  Alice   0.3
   area  pop  desc
b     2  May   0.2
   area    pop  desc
c     3  Alice   0.3

In [28]:
'''數值運算'''
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0,10,4))
pprint.pprint(ser)
df = pd.DataFrame(rng.randint(0,10,(3,4)),columns=['A','B','C','D'])
pprint.pprint(df)
#保留索引
pprint.pprint(np.exp(ser))
pprint.pprint(np.sin(df*np.pi/4))
#索引對齊
area = pd.Series({'Taipei':213,'Losangle':5322,'Taichung':65},name='area')
population = pd.Series({'Losangle':123,'b':'afb','c':1.0,'d':4325,'Taipei':1123},name='population')
#得到交集(沒有會出現NAN)
pprint.pprint(population/area)
pprint.pprint(population+area)
pprint.pprint(population.index | area.index)
#處理NAN值
A = pd.Series([2,4,6],index=[0,1,2])
B = pd.Series([1,3,5],index=[1,2,3])
pprint.pprint(A+B)
pprint.pprint(A.add(B,fill_value=0))
#運用在DataFrame
A = pd.DataFrame(rng.randint(0,20,(2,2)),columns=list('AB'))
B = pd.DataFrame(rng.randint(0,10,(3,3)),columns=list('ABC'))
pprint.pprint(A)
pprint.pprint(B)
pprint.pprint(A+B)
fill = A.stack().mean()
#以平均值填入NAN
pprint.pprint(A.add(B,fill_value=fill))
#DataFrame與Series運算
A = rng.randint(10,size=(3,4))
pprint.pprint(A)
pprint.pprint(A-A[0])
#轉置
df = pd.DataFrame(A,columns=list('QRST'))
pprint.pprint(df.sub(df['R'],axis=0))
pprint.pprint(df.sub(df.loc[0],axis=1))

0    6
1    3
2    7
3    4
dtype: int32
   A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4
0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64
          A             B         C             D
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16
Losangle    0.0231116
Taichung          NaN
Taipei         5.2723
b                 NaN
c                 NaN
d                 NaN
dtype: object
Losangle    5445
Taichung     NaN
Taipei      1336
b            NaN
c            NaN
d            NaN
dtype: object
Index(['Losangle', 'Taichung', 'Taipei', 'b', 'c', 'd'], dtype='object')
0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64
0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64
   A   B
0  1  11
1  5   1
   A  B  C
0  4  0  9
1  5  8  0
2  9  2  6
      A     B   C
0   5.0  11.0 NaN
1  10.0   9.0 NaN
2   NaN   NaN NaN
      A     B     C
0   5.0  11.0  13.5
1  10.0   9.0   4.5
2  13.5   6.5  10.5
array([[3, 8, 2, 4],
       [2, 6, 4, 8],
       [6, 1, 3, 8]])
array([[ 0,  0,  0,  0],
       [-1, -2,  2,  4],
       [ 3, -7,  1,  4]])
   Q  R  S  T
0 -5  0 -6 -4
1 -4  0 -2  2
2  5  0  2  7
   Q  R  S  T
0  0  0  0  0
1 -1 -2  2  4
2  3 -7  1  4

In [14]:
'''缺失值'''
#物件缺失(None)
vals1 = np.array([1,None,3,4])
pprint.pprint(vals1)
#數值缺失(NaN)，特殊浮點數
vals2 = np.array([1,np.nan,3,4])
pprint.pprint(vals2)
pprint.pprint(vals2.dtype)
pprint.pprint(vals2.sum())
#忽略NaN
pprint.pprint(np.nansum(vals2))
pprint.pprint(np.nanmax(vals2))
pprint.pprint(np.nanmin(vals2))
pprint.pprint(np.nanmean(vals2))
pprint.pprint(np.nanmedian(vals2))
#在Pandas中，Nan及None可以等價交換
pprint.pprint(pd.Series([1,np.nan,2,None]))

array([1, None, 3, 4], dtype=object)
array([ 1., nan,  3.,  4.])
dtype('float64')
nan
8.0
4.0
1.0
2.6666666666666665
3.0
0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [3]:
'''處理缺失值'''
data = pd.Series([1,np.nan,2,None])
#建立判斷缺失值的掩碼
pprint.pprint(data.isnull())
#取出缺失值部分
pprint.pprint(data[data.isnull()])
#取出非缺失值部分
pprint.pprint(data[data.notnull()])
#去除缺失值
data2 = data.dropna()
pprint.pprint(data2)
#在DataFrame要注意軸
df = pd.DataFrame(np.arange(9).reshape((3,3)))
df.iloc[0,1]= np.nan
df.iloc[2,0]= np.nan
pprint.pprint(df)
pprint.pprint('!!!!!!!!!!!!!!!!!')
pprint.pprint(df.dropna())
pprint.pprint('!!!!!!!!!!!!!!!!!')
pprint.pprint(df.dropna(axis='columns'))
pprint.pprint('!!!!!!!!!!!!!!!!!')
pprint.pprint(df.dropna(axis='rows'))
pprint.pprint('!!!!!!!!!!!!!!!!!')
#要整列都是缺失值
pprint.pprint(df.dropna(axis='rows',how='all'))
pprint.pprint('!!!!!!!!!!!!!!!!!')
#非缺失值最小數量，大於刪除
pprint.pprint(df.dropna(axis='rows',thresh=2))
pprint.pprint('!!!!!!!!!!!!!!!!!')
pprint.pprint(df.dropna(axis='rows',thresh=3))

#填補缺失值
pprint.pprint(data.fillna(0))
#以前一個值補滿
pprint.pprint(data.fillna(method='ffill'))
#以後一個值補滿
pprint.pprint(data.fillna(method='bfill'))
#指定軸
pprint.pprint(df.fillna(method='ffill',axis=1))
pprint.pprint(df.fillna(method='bfill',axis=0))

0    False
1     True
2    False
3     True
dtype: bool
1   NaN
3   NaN
dtype: float64
0    1.0
2    2.0
dtype: float64
0    1.0
2    2.0
dtype: float64
     0    1  2
0  0.0  NaN  2
1  3.0  4.0  5
2  NaN  7.0  8
'!!!!!!!!!!!!!!!!!'
     0    1  2
1  3.0  4.0  5
'!!!!!!!!!!!!!!!!!'
   2
0  2
1  5
2  8
'!!!!!!!!!!!!!!!!!'
     0    1  2
1  3.0  4.0  5
'!!!!!!!!!!!!!!!!!'
     0    1  2
0  0.0  NaN  2
1  3.0  4.0  5
2  NaN  7.0  8
'!!!!!!!!!!!!!!!!!'
     0    1  2
0  0.0  NaN  2
1  3.0  4.0  5
2  NaN  7.0  8
'!!!!!!!!!!!!!!!!!'
     0    1  2
1  3.0  4.0  5
0    1.0
1    0.0
2    2.0
3    0.0
dtype: float64
0    1.0
1    1.0
2    2.0
3    2.0
dtype: float64
0    1.0
1    2.0
2    2.0
3    NaN
dtype: float64
     0    1    2
0  0.0  0.0  2.0
1  3.0  4.0  5.0
2  NaN  7.0  8.0
     0    1  2
0  0.0  4.0  2
1  3.0  4.0  5
2  NaN  7.0  8

In [3]:
'''層級索引'''
index = [('A',2000),('A',2010),('B',2000),('B',2010),('E',2000),('F',2010)]
populations = [32131,432423,5654,7546546,231231,43525]
pop = pd.Series(populations,index=index)
pprint.pprint(pop)
#建立多重索引
index = pd.MultiIndex.from_tuples(index)
pprint.pprint(index)
pop = pop.reindex(index)
#設定索引名稱
pop.index.names=['state','year']
pprint.pprint(pop)
pprint.pprint(pop[:,2010])
#多重索引Series轉換為普通索引DataFrame
#在指案例中有缺失值，型態會從int64轉為float64
pop_df = pop.unstack()
pprint.pprint(pop_df)
#轉回Series
pprint.pprint(pop_df.stack())
pop_df = pd.DataFrame({'total':pop,'under18':[1,2,3,4,5,6]})
pprint.pprint(pop_df)
f_u18 = pop_df['total']/pop_df['under18']
pprint.pprint(f_u18)
pprint.pprint(f_u18.unstack())
#顯式建立索引
pprint.pprint(pd.MultiIndex.from_arrays([['a','a','b','b'],[1,2,1,2]]))
pprint.pprint(pd.MultiIndex.from_tuples([('a',1),('a',2),('b',1),('b',2)]))
#內積
pprint.pprint(pd.MultiIndex.from_product([['a','b'],[1,2]]))

(A, 2000)      32131
(A, 2010)     432423
(B, 2000)       5654
(B, 2010)    7546546
(E, 2000)     231231
(F, 2010)      43525
dtype: int64
MultiIndex([('A', 2000),
            ('A', 2010),
            ('B', 2000),
            ('B', 2010),
            ('E', 2000),
            ('F', 2010)],
           )
state  year
A      2000      32131
       2010     432423
B      2000       5654
       2010    7546546
E      2000     231231
F      2010      43525
dtype: int64
state
A     432423
B    7546546
F      43525
dtype: int64
year       2000       2010
state
A       32131.0   432423.0
B        5654.0  7546546.0
E      231231.0        NaN
F           NaN    43525.0
state  year
A      2000      32131.0
       2010     432423.0
B      2000       5654.0
       2010    7546546.0
E      2000     231231.0
F      2010      43525.0
dtype: float64
              total  under18
state year
A     2000    32131        1
      2010   432423        2
B     2000     5654        3
      2010  7546546        4
E     2000   231231        5
F     2010    43525        6
state  year
A      2000    3.213100e+04
       2010    2.162115e+05
B      2000    1.884667e+03
       2010    1.886636e+06
E      2000    4.624620e+04
F      2010    7.254167e+03
dtype: float64
year           2000          2010
state
A      32131.000000  2.162115e+05
B       1884.666667  1.886636e+06
E      46246.200000           NaN
F               NaN  7.254167e+03
MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )
MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )
MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [7]:
'''多層次索引'''
index = pd.MultiIndex.from_product([[2013,2014],[1,2]],names=['year','visit'])
columns = pd.MultiIndex.from_product([['Bob','Alice','Jean'],['HR','Temp']],names=['subject','type'])
#模擬資料
data = np.round(np.random.rand(4,6),1)
data[:,::2]*=10
data +=37
health_data = pd.DataFrame(data,index=index,columns=columns)
pprint.pprint(health_data)
#讀取資料
pprint.pprint(health_data['Jean'])
#切片與取值
pprint.pprint(pop['A',2000])
pprint.pprint(pop['B'])
pprint.pprint(pop.loc['A':'B'])
pprint.pprint(health_data['Jean','HR'])
pprint.pprint(health_data.iloc[:2,:2])
#切片索引
idx = pd.IndexSlice
pprint.pprint(health_data.loc[idx[:,2],idx[:,'HR']])
#索引如果不按字典排序會失敗
index = pd.MultiIndex.from_product([['a','c','b'],[1,2]])
data = pd.Series(np.random.rand(6),index=index)
pprint.pprint(data)
data=data.sort_index()
pprint.pprint(data)
pprint.pprint(data['a':'b'])
#stack與unstack
pprint.pprint(pop)
pprint.pprint('!!!!!!!!!!!!!!!!!!!!!')
pprint.pprint(pop.unstack(level=0))
pprint.pprint('!!!!!!!!!!!!!!!!!!!!!')
pprint.pprint(pop.unstack(level=0))
pprint.pprint('!!!!!!!!!!!!!!!!!!!!!')
pprint.pprint(pop.unstack(level=1))
#索引重置
pop_flat = pop.reset_index(name='population')
pprint.pprint(pop_flat)
#設定多重索引
pprint.pprint(pop_flat.set_index(['state','year']))
#計算
data_mean = health_data.mean(level='year')
pprint.pprint(data_mean)
pprint.pprint(data_mean.mean(axis=1,level='type'))

subject      Bob       Alice        Jean
type          HR  Temp    HR  Temp    HR  Temp
year visit
2013 1      43.0  37.1  37.0  37.7  41.0  37.8
     2      43.0  37.5  41.0  37.3  47.0  37.1
2014 1      40.0  37.1  47.0  37.0  37.0  37.3
     2      37.0  37.2  40.0  37.8  42.0  37.8
type          HR  Temp
year visit
2013 1      41.0  37.8
     2      47.0  37.1
2014 1      37.0  37.3
     2      42.0  37.8
32131
year
2000       5654
2010    7546546
dtype: int64
state  year
A      2000      32131
       2010     432423
B      2000       5654
       2010    7546546
dtype: int64
year  visit
2013  1        41.0
      2        47.0
2014  1        37.0
      2        42.0
Name: (Jean, HR), dtype: float64
subject      Bob
type          HR  Temp
year visit
2013 1      43.0  37.1
     2      43.0  37.5
subject      Bob Alice  Jean
type          HR    HR    HR
year visit
2013 2      43.0  41.0  47.0
2014 2      37.0  40.0  42.0
a  1    0.447428
   2    0.491376
c  1    0.071553
   2    0.971496
b  1    0.282236
   2    0.507926
dtype: float64
a  1    0.447428
   2    0.491376
b  1    0.282236
   2    0.507926
c  1    0.071553
   2    0.971496
dtype: float64
a  1    0.447428
   2    0.491376
b  1    0.282236
   2    0.507926
dtype: float64
state  year
A      2000      32131
       2010     432423
B      2000       5654
       2010    7546546
E      2000     231231
F      2010      43525
dtype: int64
'!!!!!!!!!!!!!!!!!!!!!'
state         A          B         E        F
year
2000    32131.0     5654.0  231231.0      NaN
2010   432423.0  7546546.0       NaN  43525.0
'!!!!!!!!!!!!!!!!!!!!!'
state         A          B         E        F
year
2000    32131.0     5654.0  231231.0      NaN
2010   432423.0  7546546.0       NaN  43525.0
'!!!!!!!!!!!!!!!!!!!!!'
year       2000       2010
state
A       32131.0   432423.0
B        5654.0  7546546.0
E      231231.0        NaN
F           NaN    43525.0
  state  year  population
0     A  2000       32131
1     A  2010      432423
2     B  2000        5654
3     B  2010     7546546
4     E  2000      231231
5     F  2010       43525
            population
state year
A     2000       32131
      2010      432423
B     2000        5654
      2010     7546546
E     2000      231231
F     2010       43525
subject   Bob        Alice        Jean
type       HR   Temp    HR  Temp    HR   Temp
year
2013     43.0  37.30  39.0  37.5  44.0  37.45
2014     38.5  37.15  43.5  37.4  39.5  37.55
type    HR       Temp
year
2013  42.0  37.416667
2014  40.5  37.366667

In [5]:
'''合併數據'''
def make_df(cols,ind):
    data = {c:[str(c)+str(i) for i in ind] for c in cols}
    return pd.DataFrame(data,ind)
pprint.pprint(make_df('ABC',range(3)))
ser1 = pd.Series(['a','b','c'],index=[1,2,3])
ser2 = pd.Series(['d','e','f'],index=[4,5,6])
pprint.pprint(pd.concat([ser1,ser2]))
#合併高維度(預設axis=0，row)
df1 = make_df('AB',[1,2])
df2 = make_df('AB',[3,4])
pprint.pprint(df1)
pprint.pprint(df2)
pprint.pprint(pd.concat([df1,df2]))
df3 = make_df('AB',[0,1])
df4 = make_df('CD',[0,1])
pprint.pprint(df3)
pprint.pprint(df4)
pprint.pprint(pd.concat([df3,df4],axis=1))
#合併索引重複
x = make_df('AB',[0,1])
y = make_df('AB',[2,3])
y.index = x.index
pprint.pprint(x)
pprint.pprint(y)
pprint.pprint(pd.concat([x,y]))
#第一種:抓取重複錯誤
try:
    pd.concat([x,y],verify_integrity=True)
except ValueError as e:
    pprint.pprint("Value Error:{0}".format(e))
#第二種:合併後產生新索引
pprint.pprint(pd.concat([x,y],ignore_index=True))
#第三種:設定多重索引
pprint.pprint(pd.concat([x,y],keys=['x','y']))

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
1    a
2    b
3    c
4    d
5    e
6    f
dtype: object
    A   B
1  A1  B1
2  A2  B2
    A   B
3  A3  B3
4  A4  B4
    A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4
    A   B
0  A0  B0
1  A1  B1
    C   D
0  C0  D0
1  C1  D1
    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
    A   B
0  A0  B0
1  A1  B1
    A   B
0  A2  B2
1  A3  B3
    A   B
0  A0  B0
1  A1  B1
0  A2  B2
1  A3  B3
"Value Error:Indexes have overlapping values: Int64Index([0, 1], dtype='int64')"
    A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3
      A   B
x 0  A0  B0
  1  A1  B1
y 0  A2  B2
  1  A3  B3

In [6]:
'''類似join的合併'''
df5 = make_df('ABC',[1,2])
df6 = make_df('BCD',[3,4])
pprint.pprint(df5)
pprint.pprint(df6)
pprint.pprint(pd.concat([df5,df6]))
#join
pprint.pprint(pd.concat([df5,df6],join='inner'))
#設定合併欄位
pprint.pprint(pd.concat([df5,df6],join_axes=[df5.columns]))
#append(會建立新物件)
pprint.pprint(df5.append(df6))

    A   B   C
1  A1  B1  C1
2  A2  B2  C2
    B   C   D
3  B3  C3  D3
4  B4  C4  D4
     A   B   C    D
1   A1  B1  C1  NaN
2   A2  B2  C2  NaN
3  NaN  B3  C3   D3
4  NaN  B4  C4   D4
    B   C
1  B1  C1
2  B2  C2
3  B3  C3
4  B4  C4
     A   B   C
1   A1  B1  C1
2   A2  B2  C2
3  NaN  B3  C3
4  NaN  B4  C4
     A   B   C    D
1   A1  B1  C1  NaN
2   A2  B2  C2  NaN
3  NaN  B3  C3   D3
4  NaN  B4  C4   D4

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: FutureWarning: The join_axes-keyword is deprecated. Use .reindex or .reindex_like on the result to achieve the same functionality.
  # Remove the CWD from sys.path while we load stuff.
C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py:7123: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort,

In [37]:
'''merge'''
df1 = pd.DataFrame({'employee':['Bob','Jack','Lisa','Sue'],\
                    'group':['Accounting','Engineering','Engineering','HR']})
df2 = pd.DataFrame({'employee':['Lisa','Bob','Jack','Sue'],\
                    'hire_date':['2004','2008','2012','2014']})
pprint.pprint(df1)
pprint.pprint(df2)
#合併成同一個(1對1)
df3 = pd.merge(df1,df2)
pprint.pprint(df3)
#1對多
df4 = pd.DataFrame({'group':['Accounting','Engineering','HR'],\
                    'supervisor':['Carly','Guido','Steve']})
pprint.pprint(df4)
pprint.pprint(pd.merge(df3,df4))
#多對多
df5 = pd.DataFrame({'group':['Accounting','Accounting','Engineering','Engineering','HR','HR'],\
                    'skills':['math','spreadsheets','coding','linux','spreadsheets','organization']})
pprint.pprint(df5)
pprint.pprint(pd.merge(df1,df5))

#設定合併的鍵值(key)，只能在有相同欄位名稱時使用
pprint.pprint(pd.merge(df1,df2,on='employee'))

#設定左與右Dataframe不同欄位名稱做merge
df3 = pd.DataFrame({'name':['Bob','Jack','Lisa','Sue'],\
                    'salary':[70000,80000,120000,90000]})
pprint.pprint(df1)
pprint.pprint(df3)
pprint.pprint(pd.merge(df1,df3,left_on='employee',right_on='name'))
#將多餘的欄位移除
pprint.pprint(pd.merge(df1,df3,left_on='employee',right_on='name').drop('name',axis=1))
#設定合併索引(left及right)
df1a = df1.set_index('employee')
df2a = df2.set_index('employee')
pprint.pprint(df1a)
pprint.pprint(df2a)
pprint.pprint(pd.merge(df1a,df2a,left_index=True,right_index=True))
#跟上一句同等效力
pprint.pprint(df1a.join(df2a))
#混合使用
pprint.pprint(pd.merge(df1a,df3,left_index=True,right_on='name'))

  employee        group
0      Bob   Accounting
1     Jack  Engineering
2     Lisa  Engineering
3      Sue           HR
  employee hire_date
0     Lisa      2004
1      Bob      2008
2     Jack      2012
3      Sue      2014
  employee        group hire_date
0      Bob   Accounting      2008
1     Jack  Engineering      2012
2     Lisa  Engineering      2004
3      Sue           HR      2014
         group supervisor
0   Accounting      Carly
1  Engineering      Guido
2           HR      Steve
  employee        group hire_date supervisor
0      Bob   Accounting      2008      Carly
1     Jack  Engineering      2012      Guido
2     Lisa  Engineering      2004      Guido
3      Sue           HR      2014      Steve
         group        skills
0   Accounting          math
1   Accounting  spreadsheets
2  Engineering        coding
3  Engineering         linux
4           HR  spreadsheets
5           HR  organization
  employee        group        skills
0      Bob   Accounting          math
1      Bob   Accounting  spreadsheets
2     Jack  Engineering        coding
3     Jack  Engineering         linux
4     Lisa  Engineering        coding
5     Lisa  Engineering         linux
6      Sue           HR  spreadsheets
7      Sue           HR  organization
  employee        group hire_date
0      Bob   Accounting      2008
1     Jack  Engineering      2012
2     Lisa  Engineering      2004
3      Sue           HR      2014
  employee        group
0      Bob   Accounting
1     Jack  Engineering
2     Lisa  Engineering
3      Sue           HR
   name  salary
0   Bob   70000
1  Jack   80000
2  Lisa  120000
3   Sue   90000
  employee        group  name  salary
0      Bob   Accounting   Bob   70000
1     Jack  Engineering  Jack   80000
2     Lisa  Engineering  Lisa  120000
3      Sue           HR   Sue   90000
  employee        group  salary
0      Bob   Accounting   70000
1     Jack  Engineering   80000
2     Lisa  Engineering  120000
3      Sue           HR   90000
                group
employee
Bob        Accounting
Jack      Engineering
Lisa      Engineering
Sue                HR
         hire_date
employee
Lisa          2004
Bob           2008
Jack          2012
Sue           2014
                group hire_date
employee
Bob        Accounting      2008
Jack      Engineering      2012
Lisa      Engineering      2004
Sue                HR      2014
                group hire_date
employee
Bob        Accounting      2008
Jack      Engineering      2012
Lisa      Engineering      2004
Sue                HR      2014
         group  name  salary
0   Accounting   Bob   70000
1  Engineering  Jack   80000
2  Engineering  Lisa  120000
3           HR   Sue   90000

In [55]:
'''集合操作規則'''
df6 = pd.DataFrame({'name':['Peter','Paul','Mary'],\
                    'food':['fish','beans','bread']},\
                   columns=['name','food'])
df7 = pd.DataFrame({'name':['Mary','Joseph'],\
                    'drink':['wine','bear']},\
                   columns=['name','drink'])
pprint.pprint(df6)
pprint.pprint(df7)
pprint.pprint(pd.merge(df6,df7))
#交集
pprint.pprint("--------------------")
pprint.pprint(pd.merge(df6,df7,how='inner'))
#外積
pprint.pprint("--------------------")
pprint.pprint(pd.merge(df6,df7,how='outer'))
#左結合
pprint.pprint("--------------------")
pprint.pprint(pd.merge(df6,df7,how='left'))
#右結合
pprint.pprint("--------------------")
pprint.pprint(pd.merge(df6,df7,how='right'))
#檢查缺失值
pprint.pprint("--------------------")
pprint.pprint(pd.merge(df6,df7,how='right').isnull().any())
pprint.pprint("--------------------")
temp_pd = pd.merge(df6,df7,how='right')
pprint.pprint(temp_pd[temp_pd['food'].isnull()])
#處理重複欄位名稱
df8 = pd.DataFrame({'name':['Bob','Jack','Lisa','Sue'],\
                    'rank':[1,2,3,4]})
df9 = pd.DataFrame({'name':['Bob','Jack','Lisa','Sue'],\
                    'rank':[3,1,4,2]})
pprint.pprint(df8)
pprint.pprint("--------------------")
pprint.pprint(df9)
pprint.pprint("--------------------")
pprint.pprint(pd.merge(df8,df9,on='name'))
#定義重複欄位名稱
pprint.pprint("--------------------")
pprint.pprint(pd.merge(df8,df9,on='name',suffixes=['_L','_R']))

    name   food
0  Peter   fish
1   Paul  beans
2   Mary  bread
     name drink
0    Mary  wine
1  Joseph  bear
   name   food drink
0  Mary  bread  wine
'--------------------'
   name   food drink
0  Mary  bread  wine
'--------------------'
     name   food drink
0   Peter   fish   NaN
1    Paul  beans   NaN
2    Mary  bread  wine
3  Joseph    NaN  bear
'--------------------'
    name   food drink
0  Peter   fish   NaN
1   Paul  beans   NaN
2   Mary  bread  wine
'--------------------'
     name   food drink
0    Mary  bread  wine
1  Joseph    NaN  bear
'--------------------'
name     False
food      True
drink    False
dtype: bool
'--------------------'
     name food drink
1  Joseph  NaN  bear
   name  rank
0   Bob     1
1  Jack     2
2  Lisa     3
3   Sue     4
'--------------------'
   name  rank
0   Bob     3
1  Jack     1
2  Lisa     4
3   Sue     2
'--------------------'
   name  rank_x  rank_y
0   Bob       1       3
1  Jack       2       1
2  Lisa       3       4
3   Sue       4       2
'--------------------'
   name  rank_L  rank_R
0   Bob       1       3
1  Jack       2       1
2  Lisa       3       4
3   Sue       4       2

In [4]:
'''累計與分組'''
import seaborn as sns
planets = sns.load_dataset('planets')
pprint.pprint(planets.shape)
pprint.pprint(planets.head())
#顯示統計值
pprint.pprint(planets.dropna().describe())
#簡單累計
rng = np.random.RandomState(42)
ser = pd.Series(rng.rand(5))
pprint.pprint(ser)
pprint.pprint("-----------------------------")
pprint.pprint("-----------------------------")
pprint.pprint(ser.sum())
pprint.pprint(ser.mean())
pprint.pprint("-----------------------------")
#用於DataFrame
df = pd.DataFrame({'A':rng.rand(5),\
                  'B':rng.rand(5)})
pprint.pprint(df)
pprint.pprint("-----------------------------")
pprint.pprint(df.mean())
pprint.pprint("-----------------------------")
#指定行列
pprint.pprint(df.mean(axis='columns'))
pprint.pprint(df.mean(axis='rows'))
pprint.pprint("-----------------------------")
#各項利用
pprint.pprint(df.count())
pprint.pprint(df.mean())
pprint.pprint(df.median())
pprint.pprint(df.max())
pprint.pprint(df.min())
pprint.pprint(df.std())
pprint.pprint(df.var())
#平均值絕對偏差
pprint.pprint(df.mad())
pprint.pprint(df.prod())
pprint.pprint(df.sum())
pprint.pprint("-----------------------------")
#first及last
i = pd.date_range('2018-04-09', periods=4, freq='2D')
ts = pd.DataFrame({'A': [1,2,3,4]}, index=i)
pprint.pprint(ts)
pprint.pprint("-----------------------------")
#前三天
pprint.pprint(ts.first('3D'))
pprint.pprint("-----------------------------")
#後三天
pprint.pprint(ts.last('3D'))

(1035, 6)
            method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009
          number  orbital_period        mass    distance         year
count  498.00000      498.000000  498.000000  498.000000   498.000000
mean     1.73494      835.778671    2.509320   52.068213  2007.377510
std      1.17572     1469.128259    3.636274   46.596041     4.167284
min      1.00000        1.328300    0.003600    1.350000  1989.000000
25%      1.00000       38.272250    0.212500   24.497500  2005.000000
50%      1.00000      357.000000    1.245000   39.940000  2009.000000
75%      2.00000      999.600000    2.867500   59.332500  2011.000000
max      6.00000    17337.500000   25.000000  354.000000  2014.000000
0    0.374540
1    0.950714
2    0.731994
3    0.598658
4    0.156019
dtype: float64
'-----------------------------'
'-----------------------------'
2.811925491708157
0.5623850983416314
'-----------------------------'
          A         B
0  0.155995  0.020584
1  0.058084  0.969910
2  0.866176  0.832443
3  0.601115  0.212339
4  0.708073  0.181825
'-----------------------------'
A    0.477888
B    0.443420
dtype: float64
'-----------------------------'
0    0.088290
1    0.513997
2    0.849309
3    0.406727
4    0.444949
dtype: float64
A    0.477888
B    0.443420
dtype: float64
'-----------------------------'
A    5
B    5
dtype: int64
A    0.477888
B    0.443420
dtype: float64
A    0.601115
B    0.212339
dtype: float64
A    0.866176
B    0.969910
dtype: float64
A    0.058084
B    0.020584
dtype: float64
A    0.353125
B    0.426952
dtype: float64
A    0.124697
B    0.182288
dtype: float64
A    0.296679
B    0.366205
dtype: float64
A    0.003340
B    0.000642
dtype: float64
A    2.389442
B    2.217101
dtype: float64
'-----------------------------'
            A
2018-04-09  1
2018-04-11  2
2018-04-13  3
2018-04-15  4
'-----------------------------'
            A
2018-04-09  1
2018-04-11  2
'-----------------------------'
            A
2018-04-13  3
2018-04-15  4